kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eventstore-linux
  labels:
    app: eventstore-linux
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 8Gi
